import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import '../alias.dart';
import 'decorated_flex_widget.dart';

class DecoratedRow extends DecoratedFlex {
  const DecoratedRow({
    Key? key,
    EdgeInsets? padding,
    EdgeInsets? margin,
    Color? color,
    Decoration? decoration,
    Decoration? foregroundDecoration,
    BoxConstraints? constraints,
    Matrix4? transform,
    Offset? offset,
    double? width,
    double? height,
    AlignmentGeometry? alignment,
    MainAxisAlignment mainAxisAlignment = MainAxisAlignment.start,
    MainAxisSize mainAxisSize = MainAxisSize.max,
    CrossAxisAlignment crossAxisAlignment = CrossAxisAlignment.center,
    TextBaseline? textBaseline,
    ContextCallback? onPressed,
    ContextCallback? onLongPressed,
    ContextCallback? onDoubleTap,
    GestureDragEndCallback? onVerticalDragEnd,
    GestureDragEndCallback? onHorizontalDragEnd,
    HitTestBehavior? behavior,
    double itemSpacing = 0,
    Widget? divider,
    bool? visible,
    bool? expanded,
    bool? flexible,
    int? flex,
    bool forceItemSameExtent = false,
    double? elevation,
    bool material = false,
    TextStyle? textStyle,
    GlobalKey? repaintBoundaryKey,
    double? widthFactor,
    double? heightFactor,
    bool? scrollable,
    Duration? animationDuration,
    Curve? animationCurve,
    ThemeData? theme,
    Widget? topEnd,
    bool? center,
    bool sliver = false,
    VerticalDirection? verticalDirection,
    Clip clipBehavior = Clip.none,
    List<Widget> children = const [],
  }) : super(
          key: key,
          direction: Axis.horizontal,
          padding: padding,
          margin: margin,
          color: color,
          decoration: decoration,
          foregroundDecoration: foregroundDecoration,
          constraints: constraints,
          transform: transform,
          offset: offset,
          width: width,
          height: height,
          alignment: alignment,
          mainAxisAlignment: mainAxisAlignment,
          mainAxisSize: mainAxisSize,
          crossAxisAlignment: crossAxisAlignment,
          textBaseline: textBaseline,
          onPressed: onPressed,
          onLongPressed: onLongPressed,
          onDoubleTap: onDoubleTap,
          onVerticalDragEnd: onVerticalDragEnd,
          onHorizontalDragEnd: onHorizontalDragEnd,
          behavior: behavior,
          itemSpacing: itemSpacing,
          visible: visible,
          expanded: expanded,
          flexible: flexible,
          flex: flex,
          forceItemSameExtent: forceItemSameExtent,
          divider: divider,
          elevation: elevation,
          material: material,
          widthFactor: widthFactor,
          heightFactor: heightFactor,
          textStyle: textStyle,
          repaintBoundaryKey: repaintBoundaryKey,
          scrollable: scrollable,
          animationDuration: animationDuration,
          animationCurve: animationCurve,
          theme: theme,
          topEnd: topEnd,
          center: center,
          sliver: sliver,
          verticalDirection: verticalDirection,
          clipBehavior: clipBehavior,
          children: children,
        );
}
